### ISSUE TITLE
Can't get simple image to build, having permissions problem.

### ISSUE THREAD

**Issue by JamesAAllsopp** [fabianlee/terraform-libvirt-ubuntu-examples#1]
Hi,
I'm having this problem with my images not creating; any ideas on how to fix it? I'm running this as a non-root user.

> libvirt_domain.domain-ubuntu: Creating...
> 
> Error: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2020-06-17T22:03:11.974582Z qemu-system-x86_64: -drive file=/var/lib/libvirt/images/simple-os_image,format=qcow2,if=none,id=drive-virtio-disk0: Could not open '/var/lib/libvirt/images/simple-os_image': Permission denied')
> 
>   on simple.tf line 43, in resource "libvirt_domain" "domain-ubuntu":
>   43: resource "libvirt_domain" "domain-ubuntu" {
Here's the file in question
>  ls -l /var/lib/libvirt/images/simple-os_image
> -rw-r--r-- 1 root root 345702400 May 13 00:47 /var/lib/libvirt/images/simple-os_image

**Comment by fabianlee** [comment]
Go to the very bottom of my blog article in the notes, try disabling
AppArmor.

https://fabianlee.org/2020/02/22/kvm-terraform-and-cloud-init-to-create-local-kvm-resources/

**Comment by JamesAAllsopp** [comment]
Sorry, didn't realise there were notes at the bottom. Changing the security solved the problem. A bit confused as my machine doesn't have either apparmour or selinux on it.
